services:
  app:
    build:
      context: .
    container_name: home_library_app
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    env_file:
      - .env # Исправленный отступ
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:13
    container_name: home_library_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
